import {
  Zap,
  Shield,
  Monitor,
  HardDrive,
  Wifi,
  Mouse,
  Server,
  Battery,
  Cable,
  Video,
  Lock,
  Cpu,
  Globe,
  Smartphone,
} from 'lucide-react';

export const products = [
  {
    id: 'NC001',
    name: 'TYPE-C to HDTV 8-in-1 Hub',
    category: 'accessories',
    price: 2800.0,
    originalPrice: null,
    rating: 4.5,
    reviews: 45,
    badge: 'New Arrival',
    badgeColor: 'new-arrival',
    images: [
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=600&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=600&fit=crop&auto=format&q=80',
      'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&h=600&fit=crop&auto=format&q=80',
    ],
    image:
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['USB-C PD 87W', 'High-speed USB-C', '2x USB-A', 'HDTV Output', 'SD Card Reader'],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '1 year',
    description:
      'Features USB-C PD (87W), high-speed USB-C, 2x USB-A, HDTV, and SD card reader. Color: Space Gray.',
    detailedDescription:
      'This premium 8-in-1 USB-C hub transforms your laptop into a powerful workstation. With support for 87W Power Delivery, you can charge your laptop while using all other ports simultaneously. The hub features high-speed data transfer, 4K HDMI output, and multiple connectivity options making it perfect for professionals and content creators.',
    quickSpecs: {
      Connectivity: { icon: Zap, value: 'USB-C, USB-A x2, HDMI' },
      Power: { icon: Shield, value: '87W USB-C PD' },
      Video: { icon: Monitor, value: '4K@30Hz HDMI' },
    },
    specifications: {
      Connectivity: 'USB-C, USB-A x2, HDMI, SD Card',
      'Power Delivery': '87W USB-C PD',
      'Video Output': '4K@30Hz HDMI',
      'Data Transfer': 'USB 3.0 (5Gbps)',
      Compatibility: 'MacBook, Windows laptops, tablets',
      Material: 'Aluminum alloy',
      Dimensions: '110 x 45 x 12mm',
      Weight: '85g',
    },
  },
  {
    id: 'NC002',
    name: 'Stylish Leather Laptop Bag',
    category: 'accessories',
    price: 4499.0,
    originalPrice: null,
    rating: 4.7,
    reviews: 89,
    badge: 'Popular',
    badgeColor: 'bg-green-500',
    image:
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['Premium Leather', 'Laptop Protection', 'Multiple Colors', 'Professional Design'],
    inStock: true,
    shippingTime: '2-3 business days',
    warranty: '2 years',
    description: 'Premium leather laptop bag. Available in Black, Gray, and Space Blue.',
    detailedDescription:
      'Crafted from genuine premium leather, this laptop bag combines style with functionality. The padded interior provides excellent protection for laptops up to 15.6 inches, while multiple compartments keep your accessories organized. Perfect for business professionals who value both aesthetics and practicality.',
    specifications: {
      Material: 'Genuine leather exterior, soft fabric lining',
      'Laptop Size': 'Up to 15.6 inches',
      Compartments: 'Main laptop compartment, 2 front pockets, side pocket',
      Colors: 'Black, Gray, Space Blue',
      Dimensions: '40 x 30 x 8 cm',
      Weight: '800g',
      Closure: 'Magnetic snap closure',
      Strap: 'Adjustable shoulder strap (70-130cm)',
    },
  },
  {
    id: 'NC003',
    name: 'Western Digital 8TB WD Purple Surveillance Hard Drive',
    category: 'storage',
    price: 18500.0,
    originalPrice: null,
    rating: 4.8,
    reviews: 156,
    badge: 'High-Performance',
    badgeColor: 'bg-primary',
    image:
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['8TB Capacity', 'SATA 6Gb/s', 'AI Surveillance Optimized', 'Reliable Performance'],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '3 years',
    description:
      '8TB SATA 6Gb/s internal hard drive. Specifically designed for AI surveillance systems.',
    detailedDescription:
      'The WD Purple surveillance hard drive is engineered specifically for 24/7 surveillance systems. With AllFrame AI technology, it reduces frame loss and improves overall video playback. Built to handle the unique demands of surveillance workloads with enhanced reliability and performance.',
    specifications: {
      Capacity: '8TB',
      Interface: 'SATA 6Gb/s',
      'Form Factor': '3.5-inch',
      RPM: '5400 RPM',
      Cache: '256MB',
      'Workload Rate': '180TB/year',
      MTBF: '1.5 million hours',
      'Operating Temperature': '0°C to 65°C',
    },
  },
  {
    id: 'NC004',
    name: 'Universal Type-C Laptop Charger',
    category: 'accessories',
    price: 1950.0,
    originalPrice: null,
    rating: 4.4,
    reviews: 78,
    badge: 'Essential',
    badgeColor: 'bg-blue-500',
    image:
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['Universal Compatibility', 'Type-C Connector', 'Fast Charging', 'Compact Design'],
    inStock: true,
    shippingTime: '1 business day',
    warranty: '1 year',
    description:
      'High-quality replacement or spare Type-C chargers for a wide variety of laptop models.',
    detailedDescription:
      "This universal Type-C laptop charger is compatible with a wide range of laptop models from major manufacturers. Featuring fast charging technology and multiple safety protections, it's the perfect replacement or backup charger for your mobile workstation.",
    specifications: {
      Input: '100-240V AC, 50/60Hz',
      Output: '20V/3.25A, 65W',
      Connector: 'USB Type-C',
      'Cable Length': '1.8m',
      'Safety Features': 'Over-voltage, over-current, short-circuit protection',
      Compatibility: 'Most USB-C laptops',
      Certification: 'CE, FCC, RoHS',
      Weight: '320g',
    },
  },
  {
    id: 'NC005',
    name: 'TYPE-C to HDTV 8-in-1 Hub with VGA/LAN',
    category: 'accessories',
    price: 3200.0,
    originalPrice: null,
    rating: 4.6,
    reviews: 67,
    badge: 'Versatile',
    badgeColor: 'bg-purple-500',
    image:
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['LAN Port', 'SD Card Support', 'USB 3.0', 'HDMI Output', 'VGA Support'],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '1 year',
    description: 'Versatile 8-in-1 Hub with LAN, SD card, USB 3.0, HDMI, and legacy VGA support.',
    detailedDescription:
      'The ultimate connectivity solution featuring 8 ports in one compact hub. Perfect for professionals who need comprehensive connectivity options including legacy VGA support for older displays and presentations.',
    specifications: {
      Ports: 'HDMI, VGA, USB 3.0 x2, USB 2.0, RJ45 LAN, SD/TF Card',
      'HDMI Output': '4K@30Hz',
      'VGA Output': '1080P@60Hz',
      'USB Data Transfer': '5Gbps (USB 3.0)',
      Ethernet: '10/100/1000 Mbps',
      'Power Delivery': 'Up to 100W',
      Material: 'Aluminum alloy',
      Dimensions: '120 x 50 x 15mm',
    },
  },
  {
    id: 'NC006',
    name: 'Microsoft Wireless Mouse',
    category: 'accessories',
    price: 1250.0,
    originalPrice: null,
    rating: 4.3,
    reviews: 234,
    badge: 'Popular',
    badgeColor: 'bg-green-500',
    image:
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['Wireless Connectivity', 'Ergonomic Design', 'Ambidextrous', 'Long Battery Life'],
    inStock: true,
    shippingTime: '1 business day',
    warranty: '1 year',
    description:
      'Ergonomic wireless mouse designed for comfort and portability. Ambidextrous design.',
    detailedDescription:
      'This wireless mouse combines comfort, precision, and portability in a sleek design. Perfect for both office work and travel, with reliable wireless connectivity and extended battery life.',
    specifications: {
      Connectivity: '2.4GHz wireless',
      Range: 'Up to 10 meters',
      DPI: '1000 DPI',
      Buttons: '3 buttons + scroll wheel',
      Battery: '1 AA battery (included)',
      'Battery Life': 'Up to 12 months',
      Compatibility: 'Windows, macOS, Linux',
      Dimensions: '100 x 60 x 35mm',
    },
  },
  {
    id: 'NC007',
    name: 'TP-Link AX1800 Dual-Band Wi-Fi 6 Router',
    category: 'networking',
    price: 5500.0,
    originalPrice: null,
    rating: 4.7,
    reviews: 189,
    badge: 'High-Performance',
    badgeColor: 'bg-primary',
    image:
      'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['Wi-Fi 6 Technology', 'Dual-Band', 'AX1800 Speed', 'Enhanced Performance'],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '2 years',
    description:
      'Experience next-gen speeds with this Wi-Fi 6 dual-band router for enhanced network performance.',
    detailedDescription:
      'Upgrade to Wi-Fi 6 with this high-performance dual-band router. Featuring the latest wireless technology, it delivers faster speeds, increased capacity, and reduced latency for all your connected devices.',
    specifications: {
      'Wi-Fi Standard': '802.11ax (Wi-Fi 6)',
      Speed: 'AX1800 (1200 Mbps + 574 Mbps)',
      Antennas: '4 × external antennas',
      'Ethernet Ports': '4 × Gigabit LAN, 1 × Gigabit WAN',
      Processor: 'Dual-core 1.5 GHz',
      Memory: '256 MB RAM, 128 MB Flash',
      Coverage: 'Up to 1,500 sq ft',
      'Concurrent Users': '50+ devices',
    },
  },
  {
    id: 'NC008',
    name: 'Adjustable Ergonomic Laptop Stand',
    category: 'accessories',
    price: 1800.0,
    originalPrice: null,
    rating: 4.5,
    reviews: 123,
    badge: 'Bestseller',
    badgeColor: 'bg-green-500',
    image:
      'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['Height Adjustable', 'Ventilated Design', 'Portable Aluminum', 'Ergonomic'],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '2 years',
    description:
      'Height-adjustable and ventilated portable aluminum stand to improve your desk ergonomics.',
    detailedDescription:
      'Transform your workspace with this premium aluminum laptop stand. The adjustable height and angle settings help reduce neck strain and improve posture, while the ventilated design keeps your laptop cool during extended use.',
    specifications: {
      Material: 'Premium aluminum alloy',
      Adjustability: '6 height levels, 0-45° tilt',
      Compatibility: 'Laptops 10-17 inches',
      'Weight Capacity': 'Up to 8kg',
      'Folded Size': '260 x 230 x 25mm',
      Weight: '1.2kg',
      Ventilation: 'Open design for airflow',
      'Non-slip': 'Silicone pads included',
    },
  },
  {
    id: 'NC009',
    name: '5Gbps Super-Speed 8-in-1 USB-C Hub',
    category: 'accessories',
    price: 2999.5,
    originalPrice: null,
    rating: 4.6,
    reviews: 98,
    badge: 'High-Performance',
    badgeColor: 'bg-primary',
    image:
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['5Gbps USB 3.0', '4K Ultra HD', 'LAN Port', 'SD/TF Card Slots', 'PD Charging'],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '1 year',
    description:
      '8-in-1 hub supporting 4K Ultra HD, 5Gbps USB 3.0, LAN, SD/TF card slots, HDMI, and PD Charging.',
    detailedDescription:
      "Experience lightning-fast data transfer with this super-speed USB-C hub. Featuring 5Gbps USB 3.0 ports and 4K Ultra HD output, it's perfect for content creators and professionals who demand the highest performance.",
    specifications: {
      'USB Ports': '2 × USB 3.0 (5Gbps), 1 × USB 2.0',
      'Video Output': 'HDMI 4K@30Hz',
      'Card Readers': 'SD/TF card slots',
      Ethernet: 'Gigabit RJ45 LAN',
      'Power Delivery': 'Up to 100W PD',
      'Data Transfer': '5Gbps super-speed',
      Material: 'Aluminum alloy',
      'Cable Length': '15cm',
    },
  },
  {
    id: 'NC010',
    name: 'Assorted Brand Laptop Chargers',
    category: 'accessories',
    price: 1950.0,
    originalPrice: null,
    rating: 4.2,
    reviews: 167,
    badge: 'Essential',
    badgeColor: 'bg-blue-500',
    image:
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=600&fit=crop&auto=format&q=80',
    features: [
      'Multi-Brand Support',
      'HP Compatible',
      'Lenovo Compatible',
      'Dell Compatible',
      'Asus Compatible',
    ],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '1 year',
    description:
      'Chargers available for major brands including HP, Toshiba, Lenovo, Asus, Dell, Acer, and many more.',
    detailedDescription:
      'Comprehensive collection of laptop chargers compatible with major brands. Whether you need a replacement or spare charger, we have options for HP, Toshiba, Lenovo, Asus, Dell, Acer, and many other popular laptop brands.',
    specifications: {
      Compatibility: 'HP, Dell, Lenovo, Asus, Acer, Toshiba',
      'Power Range': '45W - 90W',
      'Input Voltage': '100-240V AC',
      'Cable Length': '1.5-2m',
      'Connector Types': 'Various (brand specific)',
      'Safety Features': 'Over-voltage, over-current protection',
      Certification: 'CE, FCC, RoHS',
      Warranty: '12 months',
    },
  },
  {
    id: 'NC011',
    name: 'Lenovo ThinkCentre Mini PC',
    category: 'servers',
    price: 25000.0,
    originalPrice: null,
    rating: 4.4,
    reviews: 89,
    badge: 'Compact',
    badgeColor: 'bg-orange-500',
    image:
      'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['Core i3 Processor', '8GB RAM', '500GB HDD', 'Compact Design'],
    inStock: true,
    shippingTime: '2-3 business days',
    warranty: '3 years',
    description:
      'Compact and capable mini PC with a Core i3 processor, 8GB RAM, and a 500GB Hard Drive.',
    detailedDescription:
      'This compact mini PC delivers reliable performance in a space-saving design. Perfect for office environments, digital signage, or as a secondary computer. Despite its small size, it provides full desktop functionality.',
    specifications: {
      Processor: 'Intel Core i3 (varies by model)',
      Memory: '8GB DDR4 RAM',
      Storage: '500GB HDD',
      Graphics: 'Intel UHD Graphics',
      Ports: 'USB 3.0, USB 2.0, HDMI, VGA, Ethernet',
      Wireless: 'Wi-Fi 802.11ac, Bluetooth',
      Dimensions: '182 x 179 x 34.5mm',
      'Operating System': 'Windows 10/11 Pro',
    },
  },
  {
    id: 'NC012',
    name: 'Hikvision 2MP Fixed Bullet Network Camera',
    category: 'security',
    price: 4700.0,
    originalPrice: null,
    rating: 4.6,
    reviews: 145,
    badge: 'Professional',
    badgeColor: 'bg-red-500',
    image:
      'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['2MP Resolution', 'IP67 Weather Resistant', 'H.265+ Compression', 'IR Night Vision'],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '2 years',
    description:
      'IP67 weather-resistant security camera with H.265+ compression and long-range IR night vision.',
    detailedDescription:
      'Professional-grade network security camera designed for 24/7 surveillance. Features advanced H.265+ compression for efficient storage and bandwidth usage, with excellent night vision capabilities for round-the-clock monitoring.',
    specifications: {
      Resolution: '2MP (1920 × 1080)',
      Lens: '2.8mm fixed lens',
      'IR Range': 'Up to 30m',
      'Video Compression': 'H.265+, H.265, H.264+, H.264',
      'Weather Rating': 'IP67',
      Power: '12V DC ± 25%, PoE',
      'Operating Temperature': '-30°C to +60°C',
      Network: '10/100 Mbps Ethernet',
    },
  },
  {
    id: 'NC013',
    name: 'TP-Link 300Mbps ADSL2+ Modem Router',
    category: 'networking',
    price: 2200.0,
    originalPrice: null,
    rating: 4.3,
    reviews: 178,
    badge: "Editor's Choice",
    badgeColor: 'bg-primary',
    image:
      'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['ADSL2+ Modem', '300Mbps Wi-Fi', 'Easy Installation', 'Reliable Connection'],
    inStock: true,
    shippingTime: '1 business day',
    warranty: '2 years',
    description:
      'All-in-one ADSL2+ modem and 300Mbps Wi-Fi router. Easy installation and strong, reliable Wi-Fi.',
    detailedDescription:
      'Combine your modem and router in one device with this all-in-one ADSL2+ solution. Provides reliable internet connectivity with 300Mbps Wi-Fi speeds, perfect for home and small office environments.',
    specifications: {
      'ADSL Standard': 'ADSL2/2+, ADSL, READSL',
      'Wi-Fi Speed': '300Mbps (2.4GHz)',
      Antennas: '2 × 5dBi fixed antennas',
      'Ethernet Ports': '4 × 10/100Mbps LAN',
      Security: 'WPA/WPA2, WPS',
      Firewall: 'DoS attack protection',
      Dimensions: '243 × 160 × 33mm',
      Setup: 'Web-based configuration',
    },
  },
  {
    id: 'NC014',
    name: 'Apple MacBook USB-C Charger',
    category: 'accessories',
    price: 3800.0,
    originalPrice: null,
    rating: 4.8,
    reviews: 267,
    badge: 'Apple',
    badgeColor: 'bg-gray-500',
    image:
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=600&fit=crop&auto=format&q=80',
    features: [
      'Official Apple',
      'Fast Charging',
      'Type-C Port',
      'MacBook Compatible',
      'iPad Compatible',
    ],
    inStock: true,
    shippingTime: '1-2 business days',
    warranty: '1 year',
    description:
      'Official fast-charging power adapter with a Type-C port for compatible MacBooks, iPads, and other devices.',
    detailedDescription:
      'Official Apple USB-C power adapter designed for MacBooks and iPads. Features fast charging technology and the reliability you expect from genuine Apple accessories.',
    specifications: {
      'Power Output': '61W, 67W, or 96W (model dependent)',
      Connector: 'USB-C',
      Input: '100-240V AC, 50/60Hz',
      'Cable Length': '2m (included)',
      Compatibility: 'MacBook Air, MacBook Pro, iPad Pro',
      'Fast Charging': 'Yes (compatible devices)',
      Safety: 'Over-voltage, over-current protection',
      Certification: 'Apple MFi certified',
    },
  },
  {
    id: 'NC015',
    name: 'Maxday Rechargeable Battery Charger',
    category: 'accessories',
    price: 950.0,
    originalPrice: null,
    rating: 4.1,
    reviews: 89,
    badge: 'Travel',
    badgeColor: 'bg-teal-500',
    image:
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&h=600&fit=crop&auto=format&q=80',
    features: ['AA/AAA Support', '9V Compatible', 'Ni-MH/Ni-Cd', 'Worldwide Voltage', '100-240V'],
    inStock: true,
    shippingTime: '1 business day',
    warranty: '1 year',
    description:
      'Charges AA, AAA, and 9V Ni-MH/Ni-Cd rechargeable batteries. Supports worldwide voltage (100-240V).',
    detailedDescription:
      'Universal battery charger supporting multiple battery types and sizes. Perfect for travelers with worldwide voltage compatibility and intelligent charging technology that prevents overcharging.',
    specifications: {
      'Battery Types': 'Ni-MH, Ni-Cd',
      'Battery Sizes': 'AA, AAA, 9V',
      'Charging Slots': '4 × AA/AAA, 1 × 9V',
      'Input Voltage': '100-240V AC, 50/60Hz',
      'Charging Current': 'AA/AAA: 200mA, 9V: 25mA',
      'Safety Features': 'Overcharge protection, reverse polarity',
      'LED Indicators': 'Charging status display',
      Dimensions: '140 × 105 × 35mm',
    },
  },
];
